# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
# title: A blog on Maths and related topics
title: A blog of a mathematician, c., and f.
email: quanhoang.pm@gmail.com
description: Maths should be fun, so should my blog
# twitter_username: username
github_username: quanhoang-pm
minimal_mistakes_skin: default
search: true

# Build settings
markdown: kramdown
# theme: jekyll-theme-slate # it did not work
remote_theme: mmistakes/minimal-mistakes

# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-include-cache


author:
  name   : "Quan Hoang"
  avatar : "/assets/images/avatar.jpg"
  bio    : "Sinh ra từ làng và gần toán từ nhỏ."
  links:
    # - label: "Website"
    #   icon: "fas fa-fw fa-link"
    #   url: "https://"
    # - label: "Twitter"
    #   icon: "fab fa-fw fa-twitter-square"
    #   url: "https://twitter.com/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/quanhoang-pm"
    # - label: "Instagram"
    #   icon: "fab fa-fw fa-instagram"
    #   url: "https://instagram.com/"

footer:
  links:
#     - label: "Twitter"
#       icon: "fab fa-fw fa-twitter-square"
#       url: "https://twitter.com/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/quanhoang-pm"
#     - label: "Instagram"
#       icon: "fab fa-fw fa-instagram"
#       url: "https://instagram.com/"

comments:
  provider: "utterances"
  utterances:
    src: "https://utteranc.es/client.js"
    repo: "quanhoang-pm/quanhoang-pm.github.io"
    issue_term: "pathname"
    theme: "github-light" # "github-dark"
    label: "blogComment"
    crossorigin: "anonymous"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: customPostLayout
      author_profile: false
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
